import 'package:fitness_buddy/utils/path_constants.dart';
import 'package:fitness_buddy/utils/text_constants.dart';
import 'package:fitness_buddy/data/exercise_data.dart';
import 'package:fitness_buddy/data/workout_data.dart';

class DataConstants {  

  // Workouts
  static final List<WorkoutData> workouts = [
    WorkoutData(
        id: 'workout1',
        title: TextConstants.yogaTitle,
        exercises: TextConstants.yogaExercises,
        minutes: TextConstants.yogaMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.yoga,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0.0,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
            ],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
        id: 'workout2',
        title: TextConstants.pilatesTitle,
        exercises: TextConstants.pilatesExercises,
        minutes: TextConstants.pilatesMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.pilates,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.theHundred,
            minutes: TextConstants.theHundredMinutes,
            progress: 0.0,
            video: PathConstants.recliningVideo,
            description: TextConstants.theHundredDescription,
            steps: [TextConstants.theHundredStep1, TextConstants.theHundredStep2, TextConstants.theHundredStep3],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.theRollUp,
            minutes: TextConstants.theRollUpMinutes,
            progress: 0.0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.theRollUpDescription,
            steps: [TextConstants.theRollUpStep1, TextConstants.theRollUpStep2, TextConstants.theRollUpStep3],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.theOneLegCircle,
            minutes: TextConstants.theOneLegCircleMinutes,
            progress: 0.0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.theOneLegCircleDescription,
            steps: [TextConstants.theOneLegCircleStep1, TextConstants.theOneLegCircleStep2, TextConstants.theOneLegCircleStep3],
          ),
        ]),
    WorkoutData(
        id: 'workout3',
        title: TextConstants.fullBodyTitle,
        exercises: TextConstants.fullBodyExercises,
        minutes: TextConstants.fullBodyMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.fullBody,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.squat,
            minutes: TextConstants.squatMinutes,
            progress: 0.0,
            video: PathConstants.recliningVideo,
            description: TextConstants.squatDescription,
            steps: [TextConstants.squatStep1, TextConstants.squatStep2, TextConstants.squatStep3, TextConstants.squatStep4, TextConstants.squatStep5],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.benchPress,
            minutes: TextConstants.benchPressMinutes,
            progress: 0.0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.benchPressDescription,
            steps: [TextConstants.benchPressStep1, TextConstants.benchPressStep2, TextConstants.benchPressStep3],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.pulleyFront,
            minutes: TextConstants.pulleyFrontMinutes,
            progress: 0.0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.pulleyFrontDescription,
            steps: [TextConstants.pulleyFrontStep1, TextConstants.pulleyFrontStep2, TextConstants.pulleyFrontStep3],
          ),
        ]),
    WorkoutData(
      id: 'workout4',
      title: TextConstants.stretchingTitle,
      exercises: TextConstants.stretchingExercises,
      minutes: TextConstants.stretchingMinutes,
      currentProgress: 0,
      progress: 3,
      image: PathConstants.stretching,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise1',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0.0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise2',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0.0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise3',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0.0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
  ];

  static final List<WorkoutData> homeWorkouts = [
    WorkoutData(
        id: 'workout5',
        title: TextConstants.cardioTitle,
        exercises: TextConstants.cardioExercises,
        minutes: TextConstants.cardioMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.cardio,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 1,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
            ],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.3,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.99,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
        id: 'workout6',
        title: TextConstants.armsTitle,
        exercises: TextConstants.armsExercises,
        minutes: TextConstants.armsMinutes,
        currentProgress: 1,
        progress: 20,
        image: PathConstants.cardio,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0.1,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.1,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
  ];
}
