// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ZDfTZYUelLtlzLt86e_h19CnrJqENEk',
    appId: '1:59478395338:web:6a62dc7147abbc5475e733',
    messagingSenderId: '59478395338',
    projectId: 'mc656-1219f',
    authDomain: 'mc656-1219f.firebaseapp.com',
    storageBucket: 'mc656-1219f.appspot.com',
    measurementId: 'G-NS2TK9QBDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtX92PKO2jYoGt3qcvm6Hme0gBLyBBWaU',
    appId: '1:59478395338:android:0de16cbb7c8befa875e733',
    messagingSenderId: '59478395338',
    projectId: 'mc656-1219f',
    storageBucket: 'mc656-1219f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu2vmZ5cAaU3lw1P4bcs_AL_g5EFfikgo',
    appId: '1:59478395338:ios:b19f1d5aac6a2a3075e733',
    messagingSenderId: '59478395338',
    projectId: 'mc656-1219f',
    storageBucket: 'mc656-1219f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMc656',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu2vmZ5cAaU3lw1P4bcs_AL_g5EFfikgo',
    appId: '1:59478395338:ios:b19f1d5aac6a2a3075e733',
    messagingSenderId: '59478395338',
    projectId: 'mc656-1219f',
    storageBucket: 'mc656-1219f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMc656',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ZDfTZYUelLtlzLt86e_h19CnrJqENEk',
    appId: '1:59478395338:web:037b678006674e9875e733',
    messagingSenderId: '59478395338',
    projectId: 'mc656-1219f',
    authDomain: 'mc656-1219f.firebaseapp.com',
    storageBucket: 'mc656-1219f.appspot.com',
    measurementId: 'G-V5CW4X8F46',
  );
}
