name: Flutter CI

on:
  push:
    branches:
      - main
      - features/*
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run tests
      - name: Run Tests
        run: flutter test
