name: Flutter CI
on:
  push:
    branches:
      - main
      - feature/*
      - develop
  pull_request:
    branches:
      - master
      - feature/*
      - develop

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install Dependencies
        run: |
          cd fitness_buddy
          flutter pub get

      - name: Analyze
        run: |
          cd fitness_buddy
          flutter analyze

      - name: tests
        run: |
          cd fitness_buddy
          flutter test

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'  # Executa em pull requests ou na branch 'main'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: |
          cd fitness_buddy
          flutter pub get

      - run: |
          cd fitness_buddy
          flutter clean

      - run: |
          cd fitness_buddy
          flutter build appbundle